### ISSUE TITLE
Rotate matrix elements

### ISSUE THREAD

**Issue by amaanmohamed047** [raktimbar100/HACKTOBERFEST-2022#32]
This is an implementation of a program in Java that, One by one rotates all rings of elements of a 4 x 4 matrix starting from the outermost.

**Comment by amaanmohamed047** [comment]
Can you please assign this issue to me under Hacktoberfest-2022

**Comment by raktimbar100** [comment]
> This is an implementation of a program in Java that, One by one rotates all rings of elements of a 4 x 4 matrix starting from the outermost.
Please upload the code.
