### ISSUE TITLE
LeetCode Medium-Hard Questions. 

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [raktimbar100/HACKTOBERFEST-2022#57]
Adding solutions to these questions:

1. https://leetcode.com/problems/find-kth-bit-in-nth-binary-string/
2. https://leetcode.com/problems/minimum-time-to-make-rope-colorful/
3. https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/

**Comment by raktimbar100** [comment]
Ok
